[package]
name = "bufpool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
off64 = "0.6.0"
once_cell = "1.17.1"
parking_lot = "0.12.1"
